### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Godsgrav3** [RobotExMachina/Machina.NET#10]
When using the action AxesTo you can no longer attach a tool or do MoveTo. When doing AttachTool the warning message "Attaching tool without TCP values, inconsistent results may follow...?" and when doing MoveTo the warning message "Cannot apply "Move to [300, 300, 400] mm", currently missing TCP orientation to work with...".

This issue can be fixed manually by doing the command TransformTo.

![Screenshot_3](https://user-images.githubusercontent.com/1346388/56967985-9870b100-6b62-11e9-8cb0-839c3ec8e5bd.png)

The tool will be attached to the robot. I have tested this with my own targets in RobotStudio.

A possible code fix was found here: [GitHub from wsvdyk](https://github.com/wsvdyk/Machina.NET/commit/4a70bdcc1b6e4bdeb3e060500deae4f8e6bc83ad)

With the possible fix implemented on clean source code from the RobotExMachina repo.
![Screenshot_4](https://user-images.githubusercontent.com/1346388/56969091-ba6b3300-6b64-11e9-98f9-fd7dad7fa7c3.png)

quite a few actions that are already present in Machina have been tested with this possible fix, here is a list with all the action and the result with my latest version. [Google spreadsheet](https://docs.google.com/spreadsheets/d/1KdQ7p0SnTr5-Hx9eAZ5wJFmujT-U2g8xgc5qTGqHt58/edit?usp=sharing)

**Comment by garciadelcastillo** [comment]
Wow @wsvdyk, that was some comprehensive testing... thanks a lot!

I was reviewing the fix, and it won't work. The problem with your solution is:
- You issue `AxesTo(0,0,0,0,90,0);`
- You `AttachTool(...);`
- At this point, and because of the fix, Machina believes the robot is at the previous position _before the AxesTo_, in your example `[300, 300, 400]...`. This is not correct, as that location depends on the TCP position after `AxesTo()`, which also depends on the make/model/size of the robot, all variables that Machina doesn't know... 

This problem is a consequence of a larger limitation that Machina has currently which relates to switching between absolute/relative actions and cartesian/configuration spaces. I am going to write about it here: LINK TBWritten. 

So I would strongly recommend not to apply your fix, as it will result in unpredictable behavior. A solution to your problem will be to always issue a `TransformTo` before attaching a tool.

**Comment by garciadelcastillo** [comment]
Added explanation of the origin of the problem on issue #11 

https://github.com/RobotExMachina/Machina.NET/issues/11
